global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
  format: common
  filePath: /dev/stdout

api:
  dashboard: true
  debug: true

entryPoints:
  # This will be the web container
  web:
    address: ":80"
  # This will be the websecure container
  websecure:
    address: ":443"
  # This will be the vite frontend container
  vite:
    address: ":5173"


serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
    watch: false

certificatesResolvers:
  cloudflare:
    acme:
      email: diegoflx.oliveira@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
